### PR TITLE
Update Avro CPP package to latest version and integrate boost 1.82 PR

### PR DESCRIPTION
**Pull request by nugend**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

I think this is the correct way to update the package. Should include the requested migration to libboost 1.82 correctly as well.  Haven't updated a Conda package before, so will be sure to reach out for some guidance tomorrow.

### CODE REVIEW

**Comment by nugend** [comment]
I *think* the current Linux failure is spurious. Some kinda issue untarring the source ball.

**Comment by h-vetinari** [comment]
The error on windows looks like a missing header:
```
error C2065: 'INTMAX_MAX': undeclared identifier
```
INTMAX_MAX should be [defined](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/strtoimax-strtoimax-l-wcstoimax-wcstoimax-l?view=msvc-170#return-value) in `stdint.h`.

**Comment by h-vetinari** [comment]
> I _think_ the current Linux failure is spurious. Some kinda issue untarring the source ball.

I restarted that build, agreed that failure was spurious.

**Comment by nugend** [comment]
Think I was wrong about it being spurious having tried a few more things. Seems like the Linux build can't copy the required Snappy Make find command. I'm not really sure why. I'm not having any problem with that on a Linux build vm. I tried making the copy command more direct so there was no directory based ambiguity, but no luck there.

Is there any Conda Forge project guidance on replicating the CI environment?

**Pull request closed without merging**
